[""]
    type = "archive"
    url = "https://github.com/gpakosz/.tmux/archive/refs/heads/master.zip"
    extract = true
    stripComponents = 1
    refreshPeriod = "168h"
    include = ["*/.tmux.conf"]
